global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ai_agent_ecosystem'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/prometheus-metrics'
    scrape_interval: 5s
